---
#
- get_url:
    url: https://api.bintray.com/content/jfrog/artifactory-rpms/jfrog-artifactory-oss-$latest.rpm;bt_package=jfrog-artifactory-oss-rpm
    dest: /tmp/jfrog-artifactory-oss.rpm
- yum:
    name: /tmp/jfrog-artifactory-oss.rpm
    state: present
