---
#
- group:
    name: artifactory

- user:
    name: artifactory
    group: artifactory

- package:
    name: "{{ item }}"
  with_items:
    - unzip
    - tar

- file:
    path: /opt/artifactory
    state: directory
    owner: artifactory
    group: artifactory

- unarchive:
    src: https://api.bintray.com/content/jfrog/artifactory/jfrog-artifactory-oss-$latest.zip;bt_package=jfrog-artifactory-oss-zip
    dest: /opt/artifactory
    copy: no

- file:
    path: /opt/artifactory/artifactory-oss-4.7.0/bin/installService.sh
    state: touch
    mode: "u=+x"

- command: /opt/artifactory/artifactory-oss-4.7.0/bin/installService.sh
